name: NET Build & Test

on: [push]

jobs:

  build:
  
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # install .NET Core
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.202

    # install MSBuild.exe : https://github.com/microsoft/setup-msbuild
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    # install NuGet
    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.NuGetAPIKey }}
        nuget-version: '5.x'
    
    #install dependencies
    - name: Install dependencies
      run: dotnet restore
      working-directory: CodeEvaluationTest/

    # build
    - name: Build the solution
      run: dotnet build
      working-directory: CodeEvaluationTest/

    # test
    - name: Execute unit tests
      run: dotnet test
      working-directory: CodeEvaluationTest/
